import { Container } from "@Bitforge-LLC/ui";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { type ReactNode } from "react";

import { Footer } from "@/components/footer";
import { NavBar } from "@/components/navBar";

import "@Bitforge-LLC/devtools/styles";
import { AppProviders } from "@/providers";

import "./globals.css";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  //adding suppressHydrationWarning to prevent hydration errors for next-themes
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-background text-foreground antialiased ${geistSans.variable} ${geistMono.variable} `}
      >
        <AppProviders>
          <NavBar />
          <Container className="min-h-screen items-center! border-red-500 pt-26">
            <Container className="w-[90%]!">{children}</Container>
          </Container>
          <Footer />
        </AppProviders>
      </body>
    </html>
  );
};

export default RootLayout;
